INSERT INTO products (name,description,traffic,region,device_limit,duration_days,price_cents,status,sort_order,created_at,updated_at) SELECT '体验套餐','适合日常办公、学习和轻量影音使用。','100GB','香港 / 新加坡',2,30,2999,'active',10,NOW(),NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name='体验套餐');
INSERT INTO products (name,description,traffic,region,device_limit,duration_days,price_cents,status,sort_order,created_at,updated_at) SELECT '畅享套餐','适合多设备和长期稳定使用。','500GB','日本 / 美国 / 欧洲',5,90,7999,'active',20,NOW(),NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name='畅享套餐');
INSERT INTO products (name,description,traffic,region,device_limit,duration_days,price_cents,status,sort_order,created_at,updated_at) SELECT '企业定制套餐','请联系客服获取专属方案。','按需定制','多地区',10,365,29999,'draft',30,NOW(),NOW() FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM products WHERE name='企业定制套餐');
INSERT INTO product_plans(product_id,name,duration_days,price_cents,status,sort_order,created_at,updated_at) SELECT p.id,'月卡',30,2999,'active',10,NOW(),NOW() FROM products p WHERE p.name='体验套餐' AND NOT EXISTS (SELECT 1 FROM product_plans pp WHERE pp.product_id=p.id AND pp.name='月卡');
INSERT INTO product_plans(product_id,name,duration_days,price_cents,status,sort_order,created_at,updated_at) SELECT p.id,'季卡',90,7999,'active',20,NOW(),NOW() FROM products p WHERE p.name='体验套餐' AND NOT EXISTS (SELECT 1 FROM product_plans pp WHERE pp.product_id=p.id AND pp.name='季卡');
INSERT INTO product_plans(product_id,name,duration_days,price_cents,status,sort_order,created_at,updated_at) SELECT p.id,'年卡',365,28800,'active',30,NOW(),NOW() FROM products p WHERE p.name='体验套餐' AND NOT EXISTS (SELECT 1 FROM product_plans pp WHERE pp.product_id=p.id AND pp.name='年卡');
INSERT INTO product_plans(product_id,name,duration_days,price_cents,status,sort_order,created_at,updated_at) SELECT p.id,'月卡',30,8999,'active',10,NOW(),NOW() FROM products p WHERE p.name='畅享套餐' AND NOT EXISTS (SELECT 1 FROM product_plans pp WHERE pp.product_id=p.id AND pp.name='月卡');
INSERT INTO product_plans(product_id,name,duration_days,price_cents,status,sort_order,created_at,updated_at) SELECT p.id,'季卡',90,23999,'active',20,NOW(),NOW() FROM products p WHERE p.name='畅享套餐' AND NOT EXISTS (SELECT 1 FROM product_plans pp WHERE pp.product_id=p.id AND pp.name='季卡');
INSERT INTO product_plans(product_id,name,duration_days,price_cents,status,sort_order,created_at,updated_at) SELECT p.id,'年卡',365,82800,'active',30,NOW(),NOW() FROM products p WHERE p.name='畅享套餐' AND NOT EXISTS (SELECT 1 FROM product_plans pp WHERE pp.product_id=p.id AND pp.name='年卡');
