<?php
function run_migrations($pdo, $root)
{
    $sql = file_get_contents($root . '/database/schema.sql');
    foreach (array_filter(array_map('trim', preg_split('/;\s*(?:\r?\n|$)/', $sql))) as $statement) $pdo->exec($statement);
    $hasColumn = function($table, $column) use ($pdo) { $s=$pdo->prepare('SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND COLUMN_NAME=?'); $s->execute(array($table,$column)); return (int)$s->fetchColumn()>0; };
    $hasIndex = function($table, $index) use ($pdo) { $s=$pdo->prepare('SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND INDEX_NAME=?'); $s->execute(array($table,$index)); return (int)$s->fetchColumn()>0; };
    if (!$hasColumn('users','referral_code')) $pdo->exec('ALTER TABLE users ADD referral_code VARCHAR(24) NULL');
    if (!$hasIndex('users','uk_user_referral_code')) $pdo->exec('ALTER TABLE users ADD UNIQUE KEY uk_user_referral_code(referral_code)');
    $missingUsers=$pdo->query('SELECT id FROM users WHERE referral_code IS NULL OR referral_code=""')->fetchAll();$setReferral=$pdo->prepare('UPDATE users SET referral_code=? WHERE id=? AND (referral_code IS NULL OR referral_code="")');foreach($missingUsers as $missing){do{$code='R'.strtoupper(substr(bin2hex(random_bytes(10)),0,20));$check=$pdo->prepare('SELECT COUNT(*) FROM users WHERE referral_code=?');$check->execute(array($code));}while((int)$check->fetchColumn()>0);$setReferral->execute(array($code,$missing['id']));}
    if (!$hasColumn('orders','product_plan_id')) $pdo->exec('ALTER TABLE orders ADD product_plan_id BIGINT UNSIGNED NULL, ADD KEY idx_order_plan(product_plan_id)');
    if (!$hasColumn('orders','payment_started_at')) $pdo->exec('ALTER TABLE orders ADD payment_started_at DATETIME NULL');
    if (!$hasColumn('orders','plan_name_snapshot')) $pdo->exec("ALTER TABLE orders ADD plan_name_snapshot VARCHAR(100) NOT NULL DEFAULT ''");
    $paymentColumns=array('gateway_trade_no'=>"VARCHAR(100) NOT NULL DEFAULT ''",'gateway_order_no'=>"VARCHAR(64) NOT NULL DEFAULT ''",'gateway_type'=>"VARCHAR(20) NOT NULL DEFAULT ''",'payment_url'=>"VARCHAR(1000) NOT NULL DEFAULT ''",'paid_at'=>'DATETIME NULL','notify_payload'=>'TEXT NULL');
    foreach($paymentColumns as $column=>$definition) if(!$hasColumn('payment_records',$column)) $pdo->exec('ALTER TABLE payment_records ADD '.$column.' '.$definition);
    $orderColumns=array('cancelled_at'=>'DATETIME NULL','cancelled_by_type'=>'VARCHAR(20) NULL','cancelled_by_id'=>'BIGINT UNSIGNED NULL','cancel_reason'=>"VARCHAR(500) NOT NULL DEFAULT ''",'refund_requested_at'=>'DATETIME NULL','refund_processed_at'=>'DATETIME NULL','refund_reason'=>"VARCHAR(500) NOT NULL DEFAULT ''");
    $orderColumns=array_merge($orderColumns,array('temporary_subscription_url'=>"VARCHAR(500) NOT NULL DEFAULT ''",'temporary_subscription_status'=>"VARCHAR(20) NOT NULL DEFAULT 'none'",'temporary_subscription_issued_at'=>'DATETIME NULL','temporary_subscription_revoked_at'=>'DATETIME NULL','original_amount_cents'=>'BIGINT UNSIGNED NOT NULL DEFAULT 0','discount_amount_cents'=>'BIGINT UNSIGNED NOT NULL DEFAULT 0','promotion_code'=>"VARCHAR(100) NOT NULL DEFAULT ''"));
    foreach($orderColumns as $column=>$definition) if(!$hasColumn('orders',$column)) $pdo->exec('ALTER TABLE orders ADD '.$column.' '.$definition);
    if (!$hasIndex('orders','idx_order_promotion_code')) $pdo->exec('ALTER TABLE orders ADD KEY idx_order_promotion_code(promotion_code)');
    $couponColumns=array('user_id'=>'BIGINT UNSIGNED NULL','min_amount_cents'=>'BIGINT UNSIGNED NOT NULL DEFAULT 0','product_plan_id'=>'BIGINT UNSIGNED NULL','used_order_id'=>'BIGINT UNSIGNED NULL');
    foreach($couponColumns as $column=>$definition) if(!$hasColumn('coupons',$column)) $pdo->exec('ALTER TABLE coupons ADD '.$column.' '.$definition);
    if (!$hasIndex('coupons','idx_coupon_user_status')) $pdo->exec('ALTER TABLE coupons ADD KEY idx_coupon_user_status(user_id,status,expires_at)');
    if (!$hasColumn('leader_rewards','coupon_id')) $pdo->exec('ALTER TABLE leader_rewards ADD coupon_id BIGINT UNSIGNED NULL AFTER order_id');
    if (!$hasColumn('lottery_prizes','min_amount_cents')) $pdo->exec('ALTER TABLE lottery_prizes ADD min_amount_cents BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER value_cents');
    if (!$hasColumn('lottery_prizes','valid_days')) $pdo->exec('ALTER TABLE lottery_prizes ADD valid_days INT UNSIGNED NOT NULL DEFAULT 30 AFTER min_amount_cents');
    $pdo->exec('UPDATE lottery_prizes p JOIN activity_settings a ON a.id=p.activity_id SET p.min_amount_cents=COALESCE(JSON_UNQUOTE(JSON_EXTRACT(a.config_json,"$.coupon_min_amount_cents")),0),p.valid_days=COALESCE(JSON_UNQUOTE(JSON_EXTRACT(a.config_json,"$.coupon_valid_days")),30) WHERE p.min_amount_cents=0 AND p.valid_days=30');
    $pdo->exec('UPDATE orders SET original_amount_cents=unit_price_cents_snapshot WHERE original_amount_cents=0 AND discount_amount_cents=0');
    $pdo->exec('CREATE TABLE IF NOT EXISTS payment_settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,gateway_url VARCHAR(500) NOT NULL DEFAULT \'https://pae.fksqy.cn/\',pid VARCHAR(40) NOT NULL DEFAULT \'\',md5_key_ciphertext MEDIUMTEXT NOT NULL,md5_key_nonce VARBINARY(32) NOT NULL,md5_key_tag VARBINARY(32) NOT NULL,enabled TINYINT(1) NOT NULL DEFAULT 0,alipay_enabled TINYINT(1) NOT NULL DEFAULT 1,wechat_enabled TINYINT(1) NOT NULL DEFAULT 1,notify_base_url VARCHAR(500) NOT NULL DEFAULT \'\',updated_by BIGINT UNSIGNED NULL,updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
    $pdo->exec('CREATE TABLE IF NOT EXISTS system_settings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,setting_key VARCHAR(80) NOT NULL UNIQUE,setting_value VARCHAR(1000) NOT NULL DEFAULT \'\',updated_by BIGINT UNSIGNED NULL,updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
    $pdo->exec('CREATE TABLE IF NOT EXISTS order_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL,event_type VARCHAR(40) NOT NULL,old_status VARCHAR(30) NULL,new_status VARCHAR(30) NULL,description VARCHAR(500) NOT NULL,actor_type VARCHAR(20) NOT NULL,actor_id BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL,KEY idx_order_event(order_id,created_at),KEY idx_order_event_type(event_type,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
    $pdo->exec('CREATE TABLE IF NOT EXISTS group_campaign_plans (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,campaign_id BIGINT UNSIGNED NOT NULL,product_plan_id BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL,UNIQUE KEY uk_group_campaign_plan(campaign_id,product_plan_id),KEY idx_group_campaign_plan_campaign(campaign_id),KEY idx_group_campaign_plan_plan(product_plan_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
    $pdo->exec('INSERT IGNORE INTO group_campaign_plans(campaign_id,product_plan_id,created_at) SELECT g.id,p.id,NOW() FROM group_campaigns g JOIN product_plans p ON p.product_id=g.product_id AND p.status="active" LEFT JOIN group_campaign_plans x ON x.campaign_id=g.id AND x.product_plan_id=p.id WHERE x.id IS NULL');
    $pdo->exec('CREATE TABLE IF NOT EXISTS notifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,type VARCHAR(40) NOT NULL,title VARCHAR(200) NOT NULL,content VARCHAR(1000) NOT NULL,order_no VARCHAR(40) NULL,read_at DATETIME NULL,created_at DATETIME NOT NULL,KEY idx_notification_user(user_id,read_at,created_at),KEY idx_notification_order(order_no)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
    $pdo->exec('CREATE TABLE IF NOT EXISTS articles (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(200) NOT NULL,category VARCHAR(40) NOT NULL DEFAULT \'使用教程\',summary VARCHAR(500) NOT NULL DEFAULT \'\',content TEXT NOT NULL,cover_style VARCHAR(30) NOT NULL DEFAULT \'blue\',status VARCHAR(20) NOT NULL DEFAULT \'draft\',published_at DATETIME NULL,created_by BIGINT UNSIGNED NULL,updated_by BIGINT UNSIGNED NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,KEY idx_article_status_publish(status,published_at),KEY idx_article_updated(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
    $pdo->exec('CREATE TABLE IF NOT EXISTS download_resources (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,app_name VARCHAR(80) NOT NULL,version VARCHAR(60) NOT NULL DEFAULT \'\',description VARCHAR(500) NOT NULL DEFAULT \'\',project_url VARCHAR(500) NOT NULL,platform VARCHAR(20) NOT NULL,filename VARCHAR(120) NOT NULL,source_url VARCHAR(500) NOT NULL,status VARCHAR(20) NOT NULL DEFAULT \'active\',sort_order INT NOT NULL DEFAULT 0,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,UNIQUE KEY uk_download_resource(app_name,platform,filename),KEY idx_download_status_platform(status,platform,sort_order)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4');
    $resources=array(array('FlClash','v0.8.98','跨平台的 Clash 代理客户端，界面简洁，适合日常使用。','https://github.com/chen08209/FlClash','Windows','FlClash-0.8.98-windows-amd64-setup.exe','https://github.com/chen08209/FlClash/releases/download/v0.8.98/FlClash-0.8.98-windows-amd64-setup.exe'),array('FlClash','v0.8.98','跨平台的 Clash 代理客户端，界面简洁，适合日常使用。','https://github.com/chen08209/FlClash','macOS','FlClash-0.8.98-macos-amd64.dmg','https://github.com/chen08209/FlClash/releases/download/v0.8.98/FlClash-0.8.98-macos-amd64.dmg'),array('FlClash','v0.8.98','跨平台的 Clash 代理客户端，界面简洁，适合日常使用。','https://github.com/chen08209/FlClash','Linux','FlClash-0.8.98-linux-amd64.AppImage','https://github.com/chen08209/FlClash/releases/download/v0.8.98/FlClash-0.8.98-linux-amd64.AppImage'),array('FlClash','v0.8.98','跨平台的 Clash 代理客户端，界面简洁，适合日常使用。','https://github.com/chen08209/FlClash','Android','FlClash-0.8.98-android-arm64-v8a.apk','https://github.com/chen08209/FlClash/releases/download/v0.8.98/FlClash-0.8.98-android-arm64-v8a.apk'),array('FlClash','v0.8.98','跨平台的 Clash 代理客户端，界面简洁，适合日常使用。','https://github.com/chen08209/FlClash','Android','FlClash-0.8.98-android-armeabi-v7a.apk','https://github.com/chen08209/FlClash/releases/download/v0.8.98/FlClash-0.8.98-android-armeabi-v7a.apk'),array('FlClash','v0.8.98','跨平台的 Clash 代理客户端，界面简洁，适合日常使用。','https://github.com/chen08209/FlClash','Android','FlClash-0.8.98-android-x86_64.apk','https://github.com/chen08209/FlClash/releases/download/v0.8.98/FlClash-0.8.98-android-x86_64.apk'));$ins=$pdo->prepare('INSERT IGNORE INTO download_resources(app_name,version,description,project_url,platform,filename,source_url,status,sort_order,created_at,updated_at) VALUES(?,?,?,?,?,?,?,"active",0,NOW(),NOW())');foreach($resources as $r)$ins->execute($r);
    $products=$pdo->query('SELECT id,duration_days,price_cents FROM products')->fetchAll();
    foreach($products as $product){$s=$pdo->prepare('SELECT id FROM product_plans WHERE product_id=? LIMIT 1');$s->execute(array($product['id']));if(!$s->fetch()){$name='默认方案';$s=$pdo->prepare('SELECT COUNT(*) FROM product_plans WHERE product_id=? AND name=?');$s->execute(array($product['id'],$name));if((int)$s->fetchColumn())$name='基础方案';$pdo->prepare('INSERT INTO product_plans(product_id,name,duration_days,price_cents,status,sort_order,created_at,updated_at) VALUES(?,?,?,? ,"active",0,NOW(),NOW())')->execute(array($product['id'],$name,$product['duration_days'],$product['price_cents']));}}
    $pdo->exec('UPDATE orders o JOIN product_plans p ON p.product_id=o.product_id AND p.duration_days=o.duration_days_snapshot AND p.price_cents=o.unit_price_cents_snapshot SET o.product_plan_id=p.id,o.plan_name_snapshot=p.name WHERE o.product_plan_id IS NULL OR o.plan_name_snapshot=""');
    $pdo->exec('UPDATE orders o JOIN product_plans p ON p.id=o.product_plan_id SET o.plan_name_snapshot=p.name WHERE o.plan_name_snapshot=""');
    return true;
}

if (PHP_SAPI === 'cli' && realpath(isset($_SERVER['SCRIPT_FILENAME']) ? $_SERVER['SCRIPT_FILENAME'] : '') === realpath(__FILE__)) {
    $config = require dirname(__DIR__) . '/config/config.php';
    require dirname(__DIR__) . '/app/Core/Database.php';
    try {
        run_migrations(Database::connect($config), dirname(__DIR__));
        echo "数据库表和多期限方案迁移完成。\n";
    } catch (Exception $e) { fwrite(STDERR, "迁移失败：" . $e->getMessage() . "\n"); exit(1); }
}
